### ISSUE TITLE
Update metrics structure

### ISSUE THREAD

**Issue by anatheka** [Cybersecurity-Certification-Hub/security-metrics#45]
We want to update the metrics structure to the following: 

```
--- # Metadata
- id: AdminMFAEnabled
- description: This rule assesses whether an [Identity] that has the property [p1:privileged] set respectively, also has the property [enforceMFA] [p2:enabled] correctly configured.
- implementationGuidelines (assessmentGuidance) /' Optional. Provide generic guidelines, keywords or questionnaire that can help to understand what the collector has to do'/
  - AMOE: “jhsdlfjjnd”
  - Clouditor-Discovery: “sjhflsjldj”
- version: 1.0 
- comments: MFA is a standard security measure for administrative users due to their extensive permissions. 
--- # Configuration data
- p1:
  - operator: ==
  - targetValue: True
- p2:
  - operator: ==
  - targetValue: True
```
